name = "PointPatterns"
uuid = "e61b41b6-3414-4803-863f-2b69057479eb"
authors = ["JÃºlio Hoffimann"]
version = "0.3.2"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"

[compat]
Distributions = "0.21, 0.22, 0.23, 0.24"
GeoStatsBase = "0.19"
Meshes = "0.10"
julia = "1.5"
